name: Deploy
on:
  push:
    branches:
      - main
jobs:

  # Zip up the resource pack and upload to the website
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:

      # Check out the resource pack repo
      - uses: actions/checkout@v3
        with:
          path: resource-pack

      # Check out the website repo
      - uses: actions/checkout@v3
        with:
          repository: this-land-server/website
          path: website

      # Zip up the new resource pack
      - run: rm -f website/minecraft-vanilla-resource-pack.*
      - run: cd resource-pack/pack && zip -r ../../website/minecraft-vanilla-resource-pack.zip .
      - run: sha1sum website/minecraft-vanilla-resource-pack.zip | cut -d " " -f 1 > website/minecraft-vanilla-resource-pack.sha1

      # Set up SSH
      - name: Write SSH keys
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/id_rsa
          ssh-keyscan -H github.com > ~/.ssh/known_hosts

      # Commit the website folder changes
      - run: |
          cd website
          git config --global user.name "RowBot"
          git config --global user.email "48598026+rowanbot@users.noreply.github.com"
          git remote set-url origin "git@github.com:this-land-server/website.git"
          git add minecraft-vanilla-resource-pack.*
          git commit -m "Update the Minecraft Vanilla resource pack"
          git push origin main
